// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIgRj4VU7exMYf3Ys1JUX5dTaAzJUkdBk',
    appId: '1:1027999333562:web:e18507efc910bf894b5683',
    messagingSenderId: '1027999333562',
    projectId: 'shopsmart-cde81',
    authDomain: 'shopsmart-cde81.firebaseapp.com',
    storageBucket: 'shopsmart-cde81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARTBihisX-aEjVxvZNAkqKwRaFyGvxVhI',
    appId: '1:1027999333562:android:f1d98b007b5cd9d34b5683',
    messagingSenderId: '1027999333562',
    projectId: 'shopsmart-cde81',
    storageBucket: 'shopsmart-cde81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-9MSOJFFmNFFP8Fa9hA9pZSXyoCBZGJg',
    appId: '1:1027999333562:ios:d15ef92d83b815144b5683',
    messagingSenderId: '1027999333562',
    projectId: 'shopsmart-cde81',
    storageBucket: 'shopsmart-cde81.appspot.com',
    iosBundleId: 'com.example.shopsmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-9MSOJFFmNFFP8Fa9hA9pZSXyoCBZGJg',
    appId: '1:1027999333562:ios:d15ef92d83b815144b5683',
    messagingSenderId: '1027999333562',
    projectId: 'shopsmart-cde81',
    storageBucket: 'shopsmart-cde81.appspot.com',
    iosBundleId: 'com.example.shopsmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIgRj4VU7exMYf3Ys1JUX5dTaAzJUkdBk',
    appId: '1:1027999333562:web:eaefd9796ec7b3ea4b5683',
    messagingSenderId: '1027999333562',
    projectId: 'shopsmart-cde81',
    authDomain: 'shopsmart-cde81.firebaseapp.com',
    storageBucket: 'shopsmart-cde81.appspot.com',
  );
}
